---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests development
<%- if !@configs.nil? and @configs.has_key?('addons') -%>
addons:
  <%- if @configs['addons'].has_key?('apt') -%>
  apt:
    <%- if @configs['addons']['apt'].has_key?('sources') -%>
    sources:
      <%- @configs['addons']['apt']['sources'].each do |x| -%>
      - <%= x %>
      <%- end -%>
    <%- end -%>
    <%- if @configs['addons']['apt'].has_key?('packages') -%>
    packages:
      <%- @configs['addons']['apt']['packages'].each do |x| -%>
      - <%= x %>
      <%- end -%>
    <%- end -%>
  <%- end -%>
<%- end -%>
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
<% if @configs['allow_failures'] -%>
<%   @configs['allow_failures'].each do |allow_failures| -%>
  allow_failures:
    - rvm: <%= allow_failures['rvm'] %>
      env: <%= allow_failures['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "<%= @configs['secure'] -%>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.3.1
